### ISSUE TITLE
Registered Select element not working

### ISSUE THREAD

**Issue by bejucoo** [askask11/multi-language#1]
Hello,

I'm trying to use a `<select>` element to change the language but the page ends up using the _"en"_ values of the .json file even when I declared _"es"_ in the defaultLanguage. Also, when I change the select option, language  doesn't change.

This is the code of the element:

```
<select id="langs">
  <option value="es">español</option>
  <option value="en">english</option>
</select>
```

And this is the code I'm using to create the instance:

```
// Create an xhr instance
var xhr = new XMLHttpRequest(); 

// Define translator, create a default instance
var translator = new MultiLanguage("es", select = document.getElementById("langs").value); 

// Define target file and HTTP method to use.
xhr.open("GET", "./js/translation.json");

xhr.onreadystatechange=(e)=>{
  if(xhr.readyState === 4 && xhr.status === 200)  {
    // Get response text and parse it into JSON.
    var jsonResponse = JSON.parse(xhr.responseText); 
    translator.addSheet(jsonResponse);
  }
}

xhr.send()
```

If I don't use the `.value` in the selector I get a `Empty string passed to getElementById()` warning and an `Uncaught TypeError: this.externalJSON.concat is not a function` error.  Any help?

**Comment by askask11** [comment]
Hi,
Can you try to change the constructor of the translator to: 
```
// Define and construct translator
var translator = new MultiLanguage("es", [] , document.getElementById("langs")); 
```
And see if this works? Thanks.

**Comment by bejucoo** [comment]
Yes, now it does change the language!. It still selects English translation by default tho. I tried adding a `selected` attribute to the _"es"_ option but still no luck.

**Comment by askask11** [comment]
Hi,
  It will remember the language that the user selected on the last visit, and **override** the "default language" in your code. The value is stored in the LocalStorage of your browser. To clear this, simply go to
 "Inspect Element" -> "Application" -> "Storage" -> "Local Storage" 
Delete the KV pair with key "preferred-language"
And refresh the page, the default language should be "es."
Please let me know if this resolves your problem :)

**Comment by askask11** [comment]
The reason why the register select element doesn't work is that you may not skip a parameter of the construct like in Python.
Here is an example:
```
//Consider you have a class in Javascript:

class MyClass
{
    //Assign default values to the constructor
    constructor(a=0,b=1,c=1)
    {
    	this.a = a;
        this.b = b;
        this.c = c;
    }
}

(()=>{

//Construct an object for this class:
//In Python you can skip parameter "b" like this, but not in Javascript.

// Here, value 3 is still being assigned to b.
var obj = new MyClass(3,c=3); 

console.log("a="+obj.a);
console.log("b="+obj.b);
console.log("c="+obj.c);

//Output: a=3 b=3 c=1
})();
```

On my end, I did not check the datatype being passed onto the _externalJSON_ attribute, so that's why when you use _document.getElementById("langs").value_ it's giving that error because it **passes a string instead of an Array**. A string cannot concat an array, consequently giving an error of _method concat not found_. 

Same thing for the case without ".value", an element object being passed to an attribute that is supposed to be an array.

**Comment by bejucoo** [comment]
Got it. I cleared LocalStorage and also checked in a incognito window and it's working now. Thank you very much :)

**Comment by askask11** [comment]
That's great! You are welcome 👍
